//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ListTransactionsParamsType.
const (
	Income   ListTransactionsParamsType = "income"
	Spending ListTransactionsParamsType = "spending"
)

// Category defines model for Category.
type Category struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
}

// CategoryCreate defines model for CategoryCreate.
type CategoryCreate struct {
	Name string `json:"name"`
}

// CategoryList defines model for CategoryList.
type CategoryList struct {
	Items []Category `json:"items"`
}

// CategoryUpdate defines model for CategoryUpdate.
type CategoryUpdate struct {
	Name string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// MonthlySavings defines model for MonthlySavings.
type MonthlySavings struct {
	Months []int32 `json:"months"`
	Total  int64   `json:"total"`
	Values []int64 `json:"values"`
	Year   int32   `json:"year"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	AmountCents     int64              `json:"amount_cents"`
	CategoryId      *int64             `json:"category_id"`
	CreatedAt       time.Time          `json:"created_at"`
	Description     *string            `json:"description"`
	Id              int64              `json:"id"`
	TransactionDate openapi_types.Date `json:"transaction_date"`
}

// TransactionCreate defines model for TransactionCreate.
type TransactionCreate struct {
	AmountCents     int64              `json:"amount_cents"`
	CategoryId      *int64             `json:"category_id"`
	Description     *string            `json:"description"`
	TransactionDate openapi_types.Date `json:"transaction_date"`
}

// TransactionList defines model for TransactionList.
type TransactionList struct {
	Items []Transaction `json:"items"`
}

// TransactionUpdate defines model for TransactionUpdate.
type TransactionUpdate struct {
	AmountCents     int64              `json:"amount_cents"`
	CategoryId      *int64             `json:"category_id"`
	Description     *string            `json:"description"`
	TransactionDate openapi_types.Date `json:"transaction_date"`
}

// TransactionsSummary defines model for TransactionsSummary.
type TransactionsSummary struct {
	Income   TransactionsSummarySection `json:"income"`
	Months   []int32                    `json:"months"`
	Spending TransactionsSummarySection `json:"spending"`
	Year     int32                      `json:"year"`
}

// TransactionsSummaryRow defines model for TransactionsSummaryRow.
type TransactionsSummaryRow struct {
	Average    int64   `json:"average"`
	CategoryId int64   `json:"category_id"`
	Total      int64   `json:"total"`
	Values     []int64 `json:"values"`
}

// TransactionsSummarySection defines model for TransactionsSummarySection.
type TransactionsSummarySection struct {
	ColumnTotals []int64                  `json:"column_totals"`
	Rows         []TransactionsSummaryRow `json:"rows"`
	Total        int64                    `json:"total"`
}

// GetMonthlySavingsParams defines parameters for GetMonthlySavings.
type GetMonthlySavingsParams struct {
	Year int32 `form:"year" json:"year"`
}

// GetTransactionsSummaryParams defines parameters for GetTransactionsSummary.
type GetTransactionsSummaryParams struct {
	Year int32 `form:"year" json:"year"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// FromDate Include transactions on or after this date.
	FromDate *openapi_types.Date `form:"from_date,omitempty" json:"from_date,omitempty"`

	// StartDate Include transactions on or before this date.
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`

	// ToDate Include transactions on or before this date.
	ToDate *openapi_types.Date `form:"to_date,omitempty" json:"to_date,omitempty"`

	// CategoryId Filter by category id.
	CategoryId *int64 `form:"category_id,omitempty" json:"category_id,omitempty"`

	// Type Filter by spending (amount < 0) or income (amount > 0).
	Type *ListTransactionsParamsType `form:"type,omitempty" json:"type,omitempty"`

	// AfterDate Cursor date for pagination.
	AfterDate *openapi_types.Date `form:"after_date,omitempty" json:"after_date,omitempty"`

	// AfterId Cursor id for pagination.
	AfterId *int64 `form:"after_id,omitempty" json:"after_id,omitempty"`
}

// ListTransactionsParamsType defines parameters for ListTransactions.
type ListTransactionsParamsType string

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryCreate

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = CategoryUpdate

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = TransactionCreate

// UpdateTransactionJSONRequestBody defines body for UpdateTransaction for application/json ContentType.
type UpdateTransactionJSONRequestBody = TransactionUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get monthly net savings for a year
	// (GET /analytics/monthly-savings)
	GetMonthlySavings(w http.ResponseWriter, r *http.Request, params GetMonthlySavingsParams)
	// Get monthly spending and income summary by category
	// (GET /analytics/transactions-summary)
	GetTransactionsSummary(w http.ResponseWriter, r *http.Request, params GetTransactionsSummaryParams)
	// List categories
	// (GET /categories)
	ListCategories(w http.ResponseWriter, r *http.Request)
	// Create a category
	// (POST /categories)
	CreateCategory(w http.ResponseWriter, r *http.Request)
	// Delete a category
	// (DELETE /categories/{categoryId})
	DeleteCategory(w http.ResponseWriter, r *http.Request, categoryId int64)
	// Get a category
	// (GET /categories/{categoryId})
	GetCategory(w http.ResponseWriter, r *http.Request, categoryId int64)
	// Update a category
	// (PUT /categories/{categoryId})
	UpdateCategory(w http.ResponseWriter, r *http.Request, categoryId int64)
	// List transactions
	// (GET /transactions)
	ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams)
	// Create a transaction
	// (POST /transactions)
	CreateTransaction(w http.ResponseWriter, r *http.Request)
	// Delete a transaction
	// (DELETE /transactions/{transactionId})
	DeleteTransaction(w http.ResponseWriter, r *http.Request, transactionId int64)
	// Get a transaction
	// (GET /transactions/{transactionId})
	GetTransaction(w http.ResponseWriter, r *http.Request, transactionId int64)
	// Update a transaction
	// (PUT /transactions/{transactionId})
	UpdateTransaction(w http.ResponseWriter, r *http.Request, transactionId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetMonthlySavings operation middleware
func (siw *ServerInterfaceWrapper) GetMonthlySavings(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMonthlySavingsParams

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonthlySavings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTransactionsSummary operation middleware
func (siw *ServerInterfaceWrapper) GetTransactionsSummary(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTransactionsSummaryParams

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransactionsSummary(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCategory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCategory operation middleware
func (siw *ServerInterfaceWrapper) DeleteCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId int64

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", r.PathValue("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCategory(w, r, categoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCategory operation middleware
func (siw *ServerInterfaceWrapper) GetCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId int64

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", r.PathValue("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCategory(w, r, categoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCategory operation middleware
func (siw *ServerInterfaceWrapper) UpdateCategory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId int64

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", r.PathValue("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCategory(w, r, categoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "from_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "from_date", r.URL.Query(), &params.FromDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from_date", Err: err})
		return
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", r.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Optional query parameter "to_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "to_date", r.URL.Query(), &params.ToDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to_date", Err: err})
		return
	}

	// ------------- Optional query parameter "category_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "category_id", r.URL.Query(), &params.CategoryId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category_id", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "after_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "after_date", r.URL.Query(), &params.AfterDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_date", Err: err})
		return
	}

	// ------------- Optional query parameter "after_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "after_id", r.URL.Query(), &params.AfterId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTransactions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateTransaction(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTransaction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTransaction operation middleware
func (siw *ServerInterfaceWrapper) DeleteTransaction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", r.PathValue("transactionId"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transactionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTransaction(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTransaction operation middleware
func (siw *ServerInterfaceWrapper) GetTransaction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", r.PathValue("transactionId"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transactionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransaction(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTransaction operation middleware
func (siw *ServerInterfaceWrapper) UpdateTransaction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", r.PathValue("transactionId"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transactionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTransaction(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/analytics/monthly-savings", wrapper.GetMonthlySavings)
	m.HandleFunc("GET "+options.BaseURL+"/analytics/transactions-summary", wrapper.GetTransactionsSummary)
	m.HandleFunc("GET "+options.BaseURL+"/categories", wrapper.ListCategories)
	m.HandleFunc("POST "+options.BaseURL+"/categories", wrapper.CreateCategory)
	m.HandleFunc("DELETE "+options.BaseURL+"/categories/{categoryId}", wrapper.DeleteCategory)
	m.HandleFunc("GET "+options.BaseURL+"/categories/{categoryId}", wrapper.GetCategory)
	m.HandleFunc("PUT "+options.BaseURL+"/categories/{categoryId}", wrapper.UpdateCategory)
	m.HandleFunc("GET "+options.BaseURL+"/transactions", wrapper.ListTransactions)
	m.HandleFunc("POST "+options.BaseURL+"/transactions", wrapper.CreateTransaction)
	m.HandleFunc("DELETE "+options.BaseURL+"/transactions/{transactionId}", wrapper.DeleteTransaction)
	m.HandleFunc("GET "+options.BaseURL+"/transactions/{transactionId}", wrapper.GetTransaction)
	m.HandleFunc("PUT "+options.BaseURL+"/transactions/{transactionId}", wrapper.UpdateTransaction)

	return m
}

type GetMonthlySavingsRequestObject struct {
	Params GetMonthlySavingsParams
}

type GetMonthlySavingsResponseObject interface {
	VisitGetMonthlySavingsResponse(w http.ResponseWriter) error
}

type GetMonthlySavings200ResponseHeaders struct {
	XRequestID string
}

type GetMonthlySavings200JSONResponse struct {
	Body    MonthlySavings
	Headers GetMonthlySavings200ResponseHeaders
}

func (response GetMonthlySavings200JSONResponse) VisitGetMonthlySavingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetMonthlySavings400ResponseHeaders struct {
	XRequestID string
}

type GetMonthlySavings400JSONResponse struct {
	Body    Error
	Headers GetMonthlySavings400ResponseHeaders
}

func (response GetMonthlySavings400JSONResponse) VisitGetMonthlySavingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetTransactionsSummaryRequestObject struct {
	Params GetTransactionsSummaryParams
}

type GetTransactionsSummaryResponseObject interface {
	VisitGetTransactionsSummaryResponse(w http.ResponseWriter) error
}

type GetTransactionsSummary200ResponseHeaders struct {
	XRequestID string
}

type GetTransactionsSummary200JSONResponse struct {
	Body    TransactionsSummary
	Headers GetTransactionsSummary200ResponseHeaders
}

func (response GetTransactionsSummary200JSONResponse) VisitGetTransactionsSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetTransactionsSummary400ResponseHeaders struct {
	XRequestID string
}

type GetTransactionsSummary400JSONResponse struct {
	Body    Error
	Headers GetTransactionsSummary400ResponseHeaders
}

func (response GetTransactionsSummary400JSONResponse) VisitGetTransactionsSummaryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListCategoriesRequestObject struct {
}

type ListCategoriesResponseObject interface {
	VisitListCategoriesResponse(w http.ResponseWriter) error
}

type ListCategories200ResponseHeaders struct {
	XRequestID string
}

type ListCategories200JSONResponse struct {
	Body    CategoryList
	Headers ListCategories200ResponseHeaders
}

func (response ListCategories200JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateCategoryRequestObject struct {
	Body *CreateCategoryJSONRequestBody
}

type CreateCategoryResponseObject interface {
	VisitCreateCategoryResponse(w http.ResponseWriter) error
}

type CreateCategory201ResponseHeaders struct {
	XRequestID string
}

type CreateCategory201JSONResponse struct {
	Body    Category
	Headers CreateCategory201ResponseHeaders
}

func (response CreateCategory201JSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateCategory400ResponseHeaders struct {
	XRequestID string
}

type CreateCategory400JSONResponse struct {
	Body    Error
	Headers CreateCategory400ResponseHeaders
}

func (response CreateCategory400JSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteCategoryRequestObject struct {
	CategoryId int64 `json:"categoryId"`
}

type DeleteCategoryResponseObject interface {
	VisitDeleteCategoryResponse(w http.ResponseWriter) error
}

type DeleteCategory204ResponseHeaders struct {
	XRequestID string
}

type DeleteCategory204Response struct {
	Headers DeleteCategory204ResponseHeaders
}

func (response DeleteCategory204Response) VisitDeleteCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(204)
	return nil
}

type DeleteCategory404ResponseHeaders struct {
	XRequestID string
}

type DeleteCategory404JSONResponse struct {
	Body    Error
	Headers DeleteCategory404ResponseHeaders
}

func (response DeleteCategory404JSONResponse) VisitDeleteCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetCategoryRequestObject struct {
	CategoryId int64 `json:"categoryId"`
}

type GetCategoryResponseObject interface {
	VisitGetCategoryResponse(w http.ResponseWriter) error
}

type GetCategory200ResponseHeaders struct {
	XRequestID string
}

type GetCategory200JSONResponse struct {
	Body    Category
	Headers GetCategory200ResponseHeaders
}

func (response GetCategory200JSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetCategory404ResponseHeaders struct {
	XRequestID string
}

type GetCategory404JSONResponse struct {
	Body    Error
	Headers GetCategory404ResponseHeaders
}

func (response GetCategory404JSONResponse) VisitGetCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateCategoryRequestObject struct {
	CategoryId int64 `json:"categoryId"`
	Body       *UpdateCategoryJSONRequestBody
}

type UpdateCategoryResponseObject interface {
	VisitUpdateCategoryResponse(w http.ResponseWriter) error
}

type UpdateCategory200ResponseHeaders struct {
	XRequestID string
}

type UpdateCategory200JSONResponse struct {
	Body    Category
	Headers UpdateCategory200ResponseHeaders
}

func (response UpdateCategory200JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateCategory400ResponseHeaders struct {
	XRequestID string
}

type UpdateCategory400JSONResponse struct {
	Body    Error
	Headers UpdateCategory400ResponseHeaders
}

func (response UpdateCategory400JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateCategory404ResponseHeaders struct {
	XRequestID string
}

type UpdateCategory404JSONResponse struct {
	Body    Error
	Headers UpdateCategory404ResponseHeaders
}

func (response UpdateCategory404JSONResponse) VisitUpdateCategoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListTransactionsRequestObject struct {
	Params ListTransactionsParams
}

type ListTransactionsResponseObject interface {
	VisitListTransactionsResponse(w http.ResponseWriter) error
}

type ListTransactions200ResponseHeaders struct {
	XRequestID string
}

type ListTransactions200JSONResponse struct {
	Body    TransactionList
	Headers ListTransactions200ResponseHeaders
}

func (response ListTransactions200JSONResponse) VisitListTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListTransactions400ResponseHeaders struct {
	XRequestID string
}

type ListTransactions400JSONResponse struct {
	Body    Error
	Headers ListTransactions400ResponseHeaders
}

func (response ListTransactions400JSONResponse) VisitListTransactionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateTransactionRequestObject struct {
	Body *CreateTransactionJSONRequestBody
}

type CreateTransactionResponseObject interface {
	VisitCreateTransactionResponse(w http.ResponseWriter) error
}

type CreateTransaction201ResponseHeaders struct {
	XRequestID string
}

type CreateTransaction201JSONResponse struct {
	Body    Transaction
	Headers CreateTransaction201ResponseHeaders
}

func (response CreateTransaction201JSONResponse) VisitCreateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateTransaction400ResponseHeaders struct {
	XRequestID string
}

type CreateTransaction400JSONResponse struct {
	Body    Error
	Headers CreateTransaction400ResponseHeaders
}

func (response CreateTransaction400JSONResponse) VisitCreateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteTransactionRequestObject struct {
	TransactionId int64 `json:"transactionId"`
}

type DeleteTransactionResponseObject interface {
	VisitDeleteTransactionResponse(w http.ResponseWriter) error
}

type DeleteTransaction204ResponseHeaders struct {
	XRequestID string
}

type DeleteTransaction204Response struct {
	Headers DeleteTransaction204ResponseHeaders
}

func (response DeleteTransaction204Response) VisitDeleteTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(204)
	return nil
}

type DeleteTransaction404ResponseHeaders struct {
	XRequestID string
}

type DeleteTransaction404JSONResponse struct {
	Body    Error
	Headers DeleteTransaction404ResponseHeaders
}

func (response DeleteTransaction404JSONResponse) VisitDeleteTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetTransactionRequestObject struct {
	TransactionId int64 `json:"transactionId"`
}

type GetTransactionResponseObject interface {
	VisitGetTransactionResponse(w http.ResponseWriter) error
}

type GetTransaction200ResponseHeaders struct {
	XRequestID string
}

type GetTransaction200JSONResponse struct {
	Body    Transaction
	Headers GetTransaction200ResponseHeaders
}

func (response GetTransaction200JSONResponse) VisitGetTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetTransaction404ResponseHeaders struct {
	XRequestID string
}

type GetTransaction404JSONResponse struct {
	Body    Error
	Headers GetTransaction404ResponseHeaders
}

func (response GetTransaction404JSONResponse) VisitGetTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateTransactionRequestObject struct {
	TransactionId int64 `json:"transactionId"`
	Body          *UpdateTransactionJSONRequestBody
}

type UpdateTransactionResponseObject interface {
	VisitUpdateTransactionResponse(w http.ResponseWriter) error
}

type UpdateTransaction200ResponseHeaders struct {
	XRequestID string
}

type UpdateTransaction200JSONResponse struct {
	Body    Transaction
	Headers UpdateTransaction200ResponseHeaders
}

func (response UpdateTransaction200JSONResponse) VisitUpdateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateTransaction400ResponseHeaders struct {
	XRequestID string
}

type UpdateTransaction400JSONResponse struct {
	Body    Error
	Headers UpdateTransaction400ResponseHeaders
}

func (response UpdateTransaction400JSONResponse) VisitUpdateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateTransaction404ResponseHeaders struct {
	XRequestID string
}

type UpdateTransaction404JSONResponse struct {
	Body    Error
	Headers UpdateTransaction404ResponseHeaders
}

func (response UpdateTransaction404JSONResponse) VisitUpdateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get monthly net savings for a year
	// (GET /analytics/monthly-savings)
	GetMonthlySavings(ctx context.Context, request GetMonthlySavingsRequestObject) (GetMonthlySavingsResponseObject, error)
	// Get monthly spending and income summary by category
	// (GET /analytics/transactions-summary)
	GetTransactionsSummary(ctx context.Context, request GetTransactionsSummaryRequestObject) (GetTransactionsSummaryResponseObject, error)
	// List categories
	// (GET /categories)
	ListCategories(ctx context.Context, request ListCategoriesRequestObject) (ListCategoriesResponseObject, error)
	// Create a category
	// (POST /categories)
	CreateCategory(ctx context.Context, request CreateCategoryRequestObject) (CreateCategoryResponseObject, error)
	// Delete a category
	// (DELETE /categories/{categoryId})
	DeleteCategory(ctx context.Context, request DeleteCategoryRequestObject) (DeleteCategoryResponseObject, error)
	// Get a category
	// (GET /categories/{categoryId})
	GetCategory(ctx context.Context, request GetCategoryRequestObject) (GetCategoryResponseObject, error)
	// Update a category
	// (PUT /categories/{categoryId})
	UpdateCategory(ctx context.Context, request UpdateCategoryRequestObject) (UpdateCategoryResponseObject, error)
	// List transactions
	// (GET /transactions)
	ListTransactions(ctx context.Context, request ListTransactionsRequestObject) (ListTransactionsResponseObject, error)
	// Create a transaction
	// (POST /transactions)
	CreateTransaction(ctx context.Context, request CreateTransactionRequestObject) (CreateTransactionResponseObject, error)
	// Delete a transaction
	// (DELETE /transactions/{transactionId})
	DeleteTransaction(ctx context.Context, request DeleteTransactionRequestObject) (DeleteTransactionResponseObject, error)
	// Get a transaction
	// (GET /transactions/{transactionId})
	GetTransaction(ctx context.Context, request GetTransactionRequestObject) (GetTransactionResponseObject, error)
	// Update a transaction
	// (PUT /transactions/{transactionId})
	UpdateTransaction(ctx context.Context, request UpdateTransactionRequestObject) (UpdateTransactionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetMonthlySavings operation middleware
func (sh *strictHandler) GetMonthlySavings(w http.ResponseWriter, r *http.Request, params GetMonthlySavingsParams) {
	var request GetMonthlySavingsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonthlySavings(ctx, request.(GetMonthlySavingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonthlySavings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMonthlySavingsResponseObject); ok {
		if err := validResponse.VisitGetMonthlySavingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTransactionsSummary operation middleware
func (sh *strictHandler) GetTransactionsSummary(w http.ResponseWriter, r *http.Request, params GetTransactionsSummaryParams) {
	var request GetTransactionsSummaryRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransactionsSummary(ctx, request.(GetTransactionsSummaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransactionsSummary")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTransactionsSummaryResponseObject); ok {
		if err := validResponse.VisitGetTransactionsSummaryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCategories operation middleware
func (sh *strictHandler) ListCategories(w http.ResponseWriter, r *http.Request) {
	var request ListCategoriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCategories(ctx, request.(ListCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCategories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCategoriesResponseObject); ok {
		if err := validResponse.VisitListCategoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCategory operation middleware
func (sh *strictHandler) CreateCategory(w http.ResponseWriter, r *http.Request) {
	var request CreateCategoryRequestObject

	var body CreateCategoryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCategory(ctx, request.(CreateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCategoryResponseObject); ok {
		if err := validResponse.VisitCreateCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCategory operation middleware
func (sh *strictHandler) DeleteCategory(w http.ResponseWriter, r *http.Request, categoryId int64) {
	var request DeleteCategoryRequestObject

	request.CategoryId = categoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCategory(ctx, request.(DeleteCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCategoryResponseObject); ok {
		if err := validResponse.VisitDeleteCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCategory operation middleware
func (sh *strictHandler) GetCategory(w http.ResponseWriter, r *http.Request, categoryId int64) {
	var request GetCategoryRequestObject

	request.CategoryId = categoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCategory(ctx, request.(GetCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCategoryResponseObject); ok {
		if err := validResponse.VisitGetCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCategory operation middleware
func (sh *strictHandler) UpdateCategory(w http.ResponseWriter, r *http.Request, categoryId int64) {
	var request UpdateCategoryRequestObject

	request.CategoryId = categoryId

	var body UpdateCategoryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCategory(ctx, request.(UpdateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCategoryResponseObject); ok {
		if err := validResponse.VisitUpdateCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTransactions operation middleware
func (sh *strictHandler) ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams) {
	var request ListTransactionsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTransactions(ctx, request.(ListTransactionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTransactions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTransactionsResponseObject); ok {
		if err := validResponse.VisitListTransactionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTransaction operation middleware
func (sh *strictHandler) CreateTransaction(w http.ResponseWriter, r *http.Request) {
	var request CreateTransactionRequestObject

	var body CreateTransactionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTransaction(ctx, request.(CreateTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTransactionResponseObject); ok {
		if err := validResponse.VisitCreateTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTransaction operation middleware
func (sh *strictHandler) DeleteTransaction(w http.ResponseWriter, r *http.Request, transactionId int64) {
	var request DeleteTransactionRequestObject

	request.TransactionId = transactionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTransaction(ctx, request.(DeleteTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTransactionResponseObject); ok {
		if err := validResponse.VisitDeleteTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTransaction operation middleware
func (sh *strictHandler) GetTransaction(w http.ResponseWriter, r *http.Request, transactionId int64) {
	var request GetTransactionRequestObject

	request.TransactionId = transactionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransaction(ctx, request.(GetTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTransactionResponseObject); ok {
		if err := validResponse.VisitGetTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTransaction operation middleware
func (sh *strictHandler) UpdateTransaction(w http.ResponseWriter, r *http.Request, transactionId int64) {
	var request UpdateTransactionRequestObject

	request.TransactionId = transactionId

	var body UpdateTransactionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTransaction(ctx, request.(UpdateTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTransactionResponseObject); ok {
		if err := validResponse.VisitUpdateTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX0/rNhT/Kpa3h10ptOGP9pC3wd0mtN276bJJkxhCJjktvkrsYDvcVajffbKdtHHi",
	"tAFCiqBvLXGPz/md3/kbHnDMs5wzYEri6AHL+BYyYj6eEQVzLhb6cy54DkJRME9iAURBck2U/jbjItOf",
	"cEIUHCiaAQ6wWuSAIyyVoGyOlwGmiXOWMvXjyfocZQrmIPRBRjLQRxsSlgEWcFdQAQmOLrW48mhQV+dq",
	"JZHffIVYaYGVHWfmWNuafheaU5vE/06lagunCjL3w/cCZjjC303XwE9L1KcryJeri4gQZNE230jbpM7f",
	"efIS1v4sBBdtqRlISeY9BFcHfbI/caZu08UFuadsLj2X6OcumHU+HR95+eTiGGDFFUl7cvGepAV039jx",
	"q+aNCyCil7INrMzvgsrslTaVCT4I/xKESRIrylkbP5LxgqnruIr1HqbEJZuuO8KXFWlKblLAkRIFeCU8",
	"IVckIGNB88qKjkuekFvUGp7rKjwcldra+PJOS0zgYrs1JdXc1JWVduKsxwL/fDy3QbkFvSGSbj1mnp53",
	"a1K6Uu/epX1cKi+KLCO+toOymNvi1dOdlagLWHl3mBoic2CJtv1ZugxVF1baBBVEPSH+wr95WHoPoizl",
	"AxDUg+XI9bcBXl3hVkkNVtb3RLDyZrtF5mmRsWsj9tkNhODfnpTO6n5+VifUwNDoEzRs7G5L9M8pm3HT",
	"HVKlkw/+BHNyWiRzUOinP8+1J0BIgyQOJ4eTUOvHc2AkpzjCx5NwcowDnJMyeKeEkXShaCynme0aD+S6",
	"bZyDKQraH0TjcJ7gCP8KqtFganmCZKBASBxd6gSDI3xXgFhUw0VUBdvafJs3Ldre6M0oo1mR4ejQA+SV",
	"FiVzzqTlyVEYWrowBcxoTfI8pbHRe/pVWm6tb9vk+YZ5Bncn/eM/fsMBvgWSGIsf8D8HX+CuAKkOzj/q",
	"7+7p8hmiCTBFZxQEmnGBlCAxZfMJrqPQLAn67pMBbbNzh8ekU5IgYRUdzzZdAqoqpYmFShIiBgqVRDTy",
	"CDL80T+oUbZWIeWBXJe7Lt76quNbI6/Pxj2Dx2dw1UwgwhJk2wlUnkQ3CxSvNhSa0uW3suZ56as79LP1",
	"sRdkkLOI2TF1HHi1QqgG1TLAOZcerOwsuFoC2cAFqU55shgcpnLwXLrFXSeIZctJh4Pf7nOQ1SjZB/jg",
	"DLTIItIZvtOH6sl5srSqpGCHP5eiH83fHYo6TDlp2/GZowrfUT178vKe/cwVmvGCJTvyq/WG49egs4vo",
	"dlo4SniPXbrfgf914Xad72sK9dS07gnXgd67M/TPhFcBzgsP1ez6a6QqVu7aelWxt0nzt1rA3kkIWwK3",
	"SnN9RNzYW9fnpn5DYUozqvDmKZD8Z6fAozDcMhMGTWzOWZwWCaC6BYgzpKfhmQKB1C2VSBs9MQvLtoIz",
	"wbNqc+xRsmsJ/QhFbmDGBWzXRCoi1OtQRfEB9PiFptoDtTkO0aTrRndT+pjKsOHe1Xj5g30ngP4twvA4",
	"RuEHDUY5bzrPAIUfOkHRN9d1A6Z5erlxJd4Nz1khJBfGDSaeczKnzIRblwKG0QM4pryZJo+699GOGWmB",
	"8xom8Hcz25ntglMutuwX6u87X6Y5a7/eHnnL4LzS3S8adrBoUI4HGg3N9KH2rdfCocnZ/c5h9zsH5f7f",
	"RI+XF3ic8rNfPoy4fGiwYPv+wQn9F11BjFrodrOIeGWs3+8i3sYuwq3ey+X/AQAA//8pljRMJi4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
