//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	AmountCents     int64              `json:"amount_cents"`
	CategoryId      *int64             `json:"category_id"`
	CreatedAt       time.Time          `json:"created_at"`
	Description     *string            `json:"description"`
	Id              int64              `json:"id"`
	TransactionDate openapi_types.Date `json:"transaction_date"`
}

// TransactionCreate defines model for TransactionCreate.
type TransactionCreate struct {
	AmountCents     int64              `json:"amount_cents"`
	CategoryId      *int64             `json:"category_id"`
	Description     *string            `json:"description"`
	TransactionDate openapi_types.Date `json:"transaction_date"`
}

// TransactionUpdate defines model for TransactionUpdate.
type TransactionUpdate struct {
	AmountCents     int64              `json:"amount_cents"`
	CategoryId      *int64             `json:"category_id"`
	Description     *string            `json:"description"`
	TransactionDate openapi_types.Date `json:"transaction_date"`
}

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = TransactionCreate

// UpdateTransactionJSONRequestBody defines body for UpdateTransaction for application/json ContentType.
type UpdateTransactionJSONRequestBody = TransactionUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a transaction
	// (POST /transactions)
	CreateTransaction(w http.ResponseWriter, r *http.Request)
	// Delete a transaction
	// (DELETE /transactions/{transactionId})
	DeleteTransaction(w http.ResponseWriter, r *http.Request, transactionId int64)
	// Get a transaction
	// (GET /transactions/{transactionId})
	GetTransaction(w http.ResponseWriter, r *http.Request, transactionId int64)
	// Update a transaction
	// (PUT /transactions/{transactionId})
	UpdateTransaction(w http.ResponseWriter, r *http.Request, transactionId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateTransaction operation middleware
func (siw *ServerInterfaceWrapper) CreateTransaction(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTransaction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTransaction operation middleware
func (siw *ServerInterfaceWrapper) DeleteTransaction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", r.PathValue("transactionId"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transactionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTransaction(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTransaction operation middleware
func (siw *ServerInterfaceWrapper) GetTransaction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", r.PathValue("transactionId"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transactionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTransaction(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTransaction operation middleware
func (siw *ServerInterfaceWrapper) UpdateTransaction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "transactionId" -------------
	var transactionId int64

	err = runtime.BindStyledParameterWithOptions("simple", "transactionId", r.PathValue("transactionId"), &transactionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transactionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTransaction(w, r, transactionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/transactions", wrapper.CreateTransaction)
	m.HandleFunc("DELETE "+options.BaseURL+"/transactions/{transactionId}", wrapper.DeleteTransaction)
	m.HandleFunc("GET "+options.BaseURL+"/transactions/{transactionId}", wrapper.GetTransaction)
	m.HandleFunc("PUT "+options.BaseURL+"/transactions/{transactionId}", wrapper.UpdateTransaction)

	return m
}

type CreateTransactionRequestObject struct {
	Body *CreateTransactionJSONRequestBody
}

type CreateTransactionResponseObject interface {
	VisitCreateTransactionResponse(w http.ResponseWriter) error
}

type CreateTransaction201ResponseHeaders struct {
	XRequestID string
}

type CreateTransaction201JSONResponse struct {
	Body    Transaction
	Headers CreateTransaction201ResponseHeaders
}

func (response CreateTransaction201JSONResponse) VisitCreateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateTransaction400ResponseHeaders struct {
	XRequestID string
}

type CreateTransaction400JSONResponse struct {
	Body    Error
	Headers CreateTransaction400ResponseHeaders
}

func (response CreateTransaction400JSONResponse) VisitCreateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteTransactionRequestObject struct {
	TransactionId int64 `json:"transactionId"`
}

type DeleteTransactionResponseObject interface {
	VisitDeleteTransactionResponse(w http.ResponseWriter) error
}

type DeleteTransaction204ResponseHeaders struct {
	XRequestID string
}

type DeleteTransaction204Response struct {
	Headers DeleteTransaction204ResponseHeaders
}

func (response DeleteTransaction204Response) VisitDeleteTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(204)
	return nil
}

type DeleteTransaction404ResponseHeaders struct {
	XRequestID string
}

type DeleteTransaction404JSONResponse struct {
	Body    Error
	Headers DeleteTransaction404ResponseHeaders
}

func (response DeleteTransaction404JSONResponse) VisitDeleteTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetTransactionRequestObject struct {
	TransactionId int64 `json:"transactionId"`
}

type GetTransactionResponseObject interface {
	VisitGetTransactionResponse(w http.ResponseWriter) error
}

type GetTransaction200ResponseHeaders struct {
	XRequestID string
}

type GetTransaction200JSONResponse struct {
	Body    Transaction
	Headers GetTransaction200ResponseHeaders
}

func (response GetTransaction200JSONResponse) VisitGetTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetTransaction404ResponseHeaders struct {
	XRequestID string
}

type GetTransaction404JSONResponse struct {
	Body    Error
	Headers GetTransaction404ResponseHeaders
}

func (response GetTransaction404JSONResponse) VisitGetTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateTransactionRequestObject struct {
	TransactionId int64 `json:"transactionId"`
	Body          *UpdateTransactionJSONRequestBody
}

type UpdateTransactionResponseObject interface {
	VisitUpdateTransactionResponse(w http.ResponseWriter) error
}

type UpdateTransaction200ResponseHeaders struct {
	XRequestID string
}

type UpdateTransaction200JSONResponse struct {
	Body    Transaction
	Headers UpdateTransaction200ResponseHeaders
}

func (response UpdateTransaction200JSONResponse) VisitUpdateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateTransaction400ResponseHeaders struct {
	XRequestID string
}

type UpdateTransaction400JSONResponse struct {
	Body    Error
	Headers UpdateTransaction400ResponseHeaders
}

func (response UpdateTransaction400JSONResponse) VisitUpdateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateTransaction404ResponseHeaders struct {
	XRequestID string
}

type UpdateTransaction404JSONResponse struct {
	Body    Error
	Headers UpdateTransaction404ResponseHeaders
}

func (response UpdateTransaction404JSONResponse) VisitUpdateTransactionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Request-ID", fmt.Sprint(response.Headers.XRequestID))
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a transaction
	// (POST /transactions)
	CreateTransaction(ctx context.Context, request CreateTransactionRequestObject) (CreateTransactionResponseObject, error)
	// Delete a transaction
	// (DELETE /transactions/{transactionId})
	DeleteTransaction(ctx context.Context, request DeleteTransactionRequestObject) (DeleteTransactionResponseObject, error)
	// Get a transaction
	// (GET /transactions/{transactionId})
	GetTransaction(ctx context.Context, request GetTransactionRequestObject) (GetTransactionResponseObject, error)
	// Update a transaction
	// (PUT /transactions/{transactionId})
	UpdateTransaction(ctx context.Context, request UpdateTransactionRequestObject) (UpdateTransactionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateTransaction operation middleware
func (sh *strictHandler) CreateTransaction(w http.ResponseWriter, r *http.Request) {
	var request CreateTransactionRequestObject

	var body CreateTransactionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTransaction(ctx, request.(CreateTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTransactionResponseObject); ok {
		if err := validResponse.VisitCreateTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTransaction operation middleware
func (sh *strictHandler) DeleteTransaction(w http.ResponseWriter, r *http.Request, transactionId int64) {
	var request DeleteTransactionRequestObject

	request.TransactionId = transactionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTransaction(ctx, request.(DeleteTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTransactionResponseObject); ok {
		if err := validResponse.VisitDeleteTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTransaction operation middleware
func (sh *strictHandler) GetTransaction(w http.ResponseWriter, r *http.Request, transactionId int64) {
	var request GetTransactionRequestObject

	request.TransactionId = transactionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTransaction(ctx, request.(GetTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTransactionResponseObject); ok {
		if err := validResponse.VisitGetTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTransaction operation middleware
func (sh *strictHandler) UpdateTransaction(w http.ResponseWriter, r *http.Request, transactionId int64) {
	var request UpdateTransactionRequestObject

	request.TransactionId = transactionId

	var body UpdateTransactionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTransaction(ctx, request.(UpdateTransactionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTransaction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTransactionResponseObject); ok {
		if err := validResponse.VisitUpdateTransactionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xW32/TMBD+V6KDR6/NWMVD3hhDU4UYCIGENE2VF18yT41t7AtSVeV/R7b7I2kyysRW",
	"0Nib69p3333f57ssIdeV0QoVOciW4PIbrHhYvrNWW78wVhu0JDFsV+gcL9EvaWEQMnBkpSqhaRhY/F5L",
	"iwKyy83BK7Y+qK9vMSdoGHyxXDmek9Sqn4FXulY0y9eYCm0rTpCBVPR6AptwUhGWaH28nBOW2i5mUgze",
	"UPV8zq/nCBnZGgcjWOSEYuavtQIITnhEssJt2nW5DAS63EqzruKOJNvzd4Drg6EtPTOPoAepj2aHfClg",
	"IAzrctupeo9Mb8PJf0Ss+xL/53zuo3IPe1+NeGbvPuz5CFIVOrQZSR4dfMCSn9aiRErefJoCgx9oXSgC",
	"0tHxKPVYtUHFjYQMTkbp6AQYGE43gdtxC0XYMNqFx+4F4X53KiCDaPR2g4q1oKNTLRb+Qq4VoQp3uTFz",
	"mYfb41sXCY091K9eWiwggxfjbZMdrzrsuP+2mi5tXo2w4YxWLvrlVXr8GABi6o4vVjz4NnKDXKAN+b8d",
	"fY5UHE3P/O/uldV/iRSoSBYSbVJom5DluVTlCFgL2a5hPIBJmj5YdXF6DdR1ykWy0vNwtTUMXF1V3C42",
	"zCY8oY4CrOvQ8bL1ayqaCGmO8f11PXsW9nc92/HNpF/ShU7WVB9U5Mnji3yhKSl0rcRfkjgKsisxgxIH",
	"Os450i+lSw/15D++fzbCAxvhHKnvAsMtr5AClsslSJ/Tjyk/vXnlw3WePuxOhXb+vV8MzRUDUw/YLn6T",
	"HHTQrT6DfmvQPVnXP9UZ95+86Ojh3vRump8BAAD//390lC9LDwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
